### ISSUE TITLE
Can't get first test to pass

### ISSUE THREAD

**Issue by davidtheclark** [MoOx/cli-for-files#1]
I started looking at this repo this morning, but I can't easily figure out what's going wrong with the one test. I just get `not ok 1 plan != count`, and can't get a log from anywhere inside the functions that are supposed to be running. Am I missing something?

**Comment by MoOx** [comment]
Probably not. It working on travis now https://travis-ci.org/MoOx/cli-for-files/builds/79070619
What version of node are you using and what is your OS ?

**Comment by davidtheclark** [comment]
Node 0.12.7, Mac Yosemite.

That's really strange. I just did a clean clone, `npm install`, then `npm test`, and got the same failure.

**Comment by davidtheclark** [comment]
Another thing to note: the process *is creating the `input.output` file*.

**Comment by MoOx** [comment]
So I guess it's ok now. Feel free to reopen if you still have issues.
