### ISSUE TITLE
Throw error instead of using process.exit ?

### ISSUE THREAD

**Issue by davidtheclark** [MoOx/cli-for-files#4]
I have two questions about the current code:

- What is the intention in the exit code numbers? Should each one be unique — or was there some other semantic intention that I'm not picking up on?
- Related: Is it important that we use `process.exit()` instead of `throw new Error()`?

Just wondering about the original intentions that aren't immediately apparent to me. Thanks!

**Comment by MoOx** [comment]
> Should each one be unique

In theory, yes.

> Is it important that we use process.exit() instead of throw new Error()?

Never thought about that to be honest. Maybe it's a better idea indeed !

**Comment by MoOx** [comment]
I found that even eslint use process.exit in the bin. So I will keep exit as they are for now.
